---
title: "BYSY project Notebook"
output: html_notebook
---  
# Figure4

***  

### Figure 4 : RFD, Init,Ter,NanoT on CEN15,14,10 and 13
#### Figure S4: RFD, Init,Ter,NanoT for the others CEN


```{r}
suppressMessages(library(GenomicRanges))
suppressMessages(library(tidyverse))
suppressMessages(library(rtracklayer))
library(patchwork)
library(ggprism)
library(ggrepel)
theme_set(theme_bw())
mypal <- c(paletteer::paletteer_d("ggthemes::Classic_20"),"grey40","black","gold","greenyellow","grey20")

`%+%` <- paste0

source("Helper_function.r")

seqinfSY <- readRDS("Data/seqinfSY.rds")
chromSY <- import("Genome_annotations/chromBYonSYgr.bed") %>% NewSeqinfo(seqin=seqinfSY) %>% sort
bs0 <- 1000
ovl <- 100000
```


Generate genomic track with chr, CEN and ORI.  

```{r message=FALSE, warning=FALSE}
CEN <- import("Genome_annotations/SY14_CEN.gff3") %>% NewSeqinfo(seqin=seqinfSY)
ARS_BYonSY <- import("Data/ars2keep_lim10k_cl1500_2_dtac1500.bed") %>% NewSeqinfo(seqin=seqinfSY)
rDNA_SY <- GRanges("CP029160.1",IRanges(3879940,3934000),strand="*",seqinfo=seqinfSY)
maskedTy_SY <- readRDS("Data/maskedTy_SY.rds")
ura3d0 <- GRanges("CP029160.1",IRanges(1051200,1051500),strand="*",seqinfo=seqinfSY,type="ura3_masked")
masked_SY <- c(maskedTy_SY,ura3d0)

CTF19 <- import("Data/ARS_SYwCTF19.bed")
CTF19 <- CTF19[overlapsAny(CTF19,ARS_BYonSY)]

geno_leg <- factor(c("CEN","ORI","rDNA","Ty_masked","ura3_masked","CTF19"),levels=rev(c("CEN","ORI","rDNA","Ty_masked","ura3_masked","CTF19")))
geno_pal <- mypal[c(9,13,17,21,25,19)]
names(geno_pal) <- geno_leg

MasterTable <- read_tsv("Data/BYSY_MasterTable_simple_Table123.tsv",show_col_types = FALSE)
ars2plot <- inner_join(as_tibble(ARS_BYonSY),MasterTable,by = join_by(name)) %>%
	mutate(center=(start+end)/2) %>%
	mutate(ars_col=case_when(Table123=="R"~"OriRep",Table1=="A"~"OriAct",T~"OriNull"))
	
ARS_BYonSY2 <- makeGRangesFromDataFrame(ars2plot,keep.extra.columns=T)
feat.list <- GRangesList(
	CEN,
	ARS_BYonSY2,
	rDNA_SY,
	maskedTy_SY,
	ura3d0,
	CTF19,
	chromSY
) 
names(feat.list) <- c(names(geno_pal),"chromBY")
feat.list <- lapply(seq_along(feat.list), function(x) {feat.list[[x]]$type=names(feat.list)[x];return(feat.list[[x]])})
feat <- do.call(c,feat.list)

geno_leg2 <- factor(c("CEN","ORI","rDNA","Ty_masked","ura3_masked","CTF19","OriNull","OriAct","OriRep"),levels=rev(c("CEN","ORI","rDNA","Ty_masked","ura3_masked","CTF19","OriNull","OriAct","OriRep")))
geno_pal2 <- mypal[c(9,13,17,21,25,19,22,7,1)]
names(geno_pal2) <- geno_leg2

pl_geno2<- lapply(seq_along(CEN), function(i) {
	ROI <- suppressWarnings(trim(CEN[i]+ovl))
	featROI <- as_tibble(feat[overlapsAny(feat,ROI)]) %>% rename(featname=name)
ggplot(featROI)+
	geom_rect(data=featROI%>% filter(type %in% c("ORI")),aes(xmin=start,xmax=end,ymin=0,ymax=1,col=type,fill=type))+	
	geom_rect(data=featROI%>% filter(type %in% c("CEN")),aes(xmin=start,xmax=end,ymin=0,ymax=1,col=type,fill=type))+	
	geom_rect(data=featROI %>% filter(type %in% c("rDNA","Ty_masked","ura3_masked")),aes(xmin=start,xmax=end,ymin=1,ymax=2,col=type,fill=type))+
	geom_rect(data=featROI%>% filter(type %in% c("CTF19")),aes(xmin=pmax(start,start(ROI)),xmax=pmin(end,end(ROI)),ymin=1,ymax=2,col=type,fill=type))+
	geom_text_repel(data=featROI%>% filter(type %in% c("ORI")),aes(x=center,y=2.4,label=featname,col=ars_col),size=2,angle=45,hjust = 0,show.legend=F,direction="x",seed=12,ylim=c(2,4),min.segment.length=10)+
#	geom_text(data=featROI%>% filter(type %in% c("ORI")),aes(x=center,y=2.4,label=featname,color=ars_col),size=2,angle=45,hjust = 0,show.legend=F)+
	coord_cartesian(ylim=c(0,2),clip = "off")+
	scale_color_manual("",values = geno_pal2,guide = guide_legend(reverse = TRUE))+
	scale_fill_manual("",values = geno_pal2,guide = guide_legend(reverse = TRUE))+
	xlab(paste0("SY coordinates [",ROI$name,"]"," (kb)"))+
	scale_x_continuous(
		guide = "prism_minor",
		labels=scales::unit_format(big.mark ="",suffix="",scale=1e-3,sep=""),
		limits=c(start(ROI),end(ROI)),
		breaks=seq(floor(start(ROI)/50000)*50000,end(ROI),50000),
		minor_breaks=seq(floor(start(ROI)/10000)*10000,end(ROI),10000),
		expand=c(0,0))+
	theme(axis.ticks.y = element_blank(),axis.text.y = element_blank(),panel.grid.major.y=element_blank(),panel.grid.minor.y=element_blank(),legend.key = element_rect(colour = "black"))+
	guides(colour="none")
})

```

### RFD with zone
```{r warning=FALSE}
bs=1000
rfd_leg <- factor(c("BY","SY"))
rfd_pal <- mypal[c(1,7)]
names(rfd_pal) <- rfd_leg

rfdBY <- import("BigWig/rfd_BYBYSY_nt.bw")
rfdSY <- import("BigWig/rfd_SYSY_nt.bw")

rfd_zone <- import("Data/bgsigMH.bed")

pl_rfd <- lapply(seq_along(CEN), function(i) {
	ROI <- suppressWarnings(trim(CEN[i]+ovl))
	featROI <- as_tibble(feat[overlapsAny(feat,ROI)]) %>% rename(featname=name) %>% filter(type %in% c("CEN","chromBY")) 
	featROI2 <- as_tibble(rfd_zone[overlapsAny(rfd_zone,ROI)]) %>% rename(featname=name)
	featROI3 <- as_tibble(masked_SY[overlapsAny(masked_SY,ROI)])
	toplot_rfd <- tibble(pos=start(ROI):end(ROI),
		rfdby=as.numeric(unlist(coverage(rfdBY,weight=rfdBY$score)[ROI])),
		rfdsy=as.numeric(unlist(coverage(rfdSY,weight=rfdSY$score)[ROI])))
	toplot_rfd2 <- toplot_rfd %>% mutate(pos = floor(pos/bs)*bs+1) %>%
		group_by(pos) %>%
		summarise(rfdby = mean(rfdby,na.rm=T),rfdsy = mean(rfdsy,na.rm=T), .groups = "drop")
pl <- ggplot(toplot_rfd2)+
	geom_rect(data=featROI3,aes(xmin=start,xmax=end,ymin=-1,ymax=1),fill=mypal[15],col=mypal[15])+
	geom_rect(data=featROI2,aes(xmin=start,xmax=end,ymin=-1,ymax=1),fill="purple",col=NA,alpha=0.3)+
	geom_vline(data=featROI%>% filter(type %in% c("CEN")),aes(xintercept=start),linetype=2,alpha=0.8)+
	geom_vline(data=featROI%>% filter(type %in% c("CEN")),aes(xintercept=end),linetype=2,alpha=0.8)+
	geom_vline(data=featROI%>% filter(type %in% c("chromBY")),aes(xintercept=start),linetype=4,alpha=0.8)+
	geom_vline(data=featROI%>% filter(type %in% c("chromBY")),aes(xintercept=end),linetype=4,alpha=0.8)+
	geom_line(aes(x=pos,y=rfdby,col="BY"),size=0.3)+
	geom_line(aes(x=pos,y=rfdsy,col="SY"),size=0.3)+
	scale_x_continuous(
		guide = "prism_minor",
		labels=scales::unit_format(big.mark ="",suffix="",scale=1e-3,sep=""),
		limits=c(start(ROI),end(ROI)),
		breaks=seq(floor(start(ROI)/50000)*50000,end(ROI),50000),
		minor_breaks=seq(floor(start(ROI)/10000)*10000,end(ROI),10000),
		expand=c(0,0))+
	coord_cartesian(ylim=c(-1,1))+
	xlab(paste0(as.character(seqnames(ROI))," [",ROI$name,"]"," (kb)"))+
	ylab("RFD")+
	scale_color_manual("",values = rfd_pal)+
	guides(colour = guide_legend(override.aes = list(size=2)))
}
)
```

### Init plots
```{r warning=FALSE}
bs=1000
rfd_leg <- factor(c("BY","SY"))
rfd_pal <- mypal[c(1,7)]
names(rfd_pal) <- rfd_leg

initBY <- import("BigWig/ICgn_BY.bw")
initSY <- import("BigWig/ICgn_SY.bw")

init_ARS <- import("Data/ARSinitMAnorm2_1e-2.bed")


pl_init <- lapply(seq_along(CEN), function(i) {
	ROI <- suppressWarnings(trim(CEN[i]+ovl))
	featROI <- as_tibble(feat[overlapsAny(feat,ROI)]) %>% rename(featname=name) %>% filter(type %in% c("CEN","chromBY")) 
	featROI2 <- as_tibble(init_ARS[overlapsAny(init_ARS,ROI)]) %>% rename(featname=name)
	featROI3 <- as_tibble(masked_SY[overlapsAny(masked_SY,ROI)])
	toplot_init <- tibble(pos=start(ROI):end(ROI),
		initby=as.numeric(unlist(coverage(initBY,weight=initBY$score)[ROI])),
		initsy=as.numeric(unlist(coverage(initSY,weight=initSY$score)[ROI]))
		)
	toplot_init2 <- toplot_init %>% mutate(pos = floor(pos/bs)*bs+1) %>%
		group_by(pos) %>%
		summarise(
		initby = mean(initby,na.rm=T),initsy = mean(initsy,na.rm=T),
		 .groups = "drop")
	pl <- ggplot(toplot_init2)+
	geom_rect(data=featROI3,aes(xmin=start,xmax=end,ymin=0,ymax=10),fill=mypal[15],col=mypal[15])+
	geom_text(data=featROI2,aes(x=start,y=7),label="*",size=8)+
	geom_vline(data=featROI%>% filter(type %in% c("CEN")),aes(xintercept=start),linetype=2,alpha=0.8)+
	geom_vline(data=featROI%>% filter(type %in% c("CEN")),aes(xintercept=end),linetype=2,alpha=0.8)+
	geom_vline(data=featROI%>% filter(type %in% c("chromBY")),aes(xintercept=start),linetype=4,alpha=0.8)+
	geom_vline(data=featROI%>% filter(type %in% c("chromBY")),aes(xintercept=end),linetype=4,alpha=0.8)+
	geom_line(aes(x=pos,y=initby,col="BY"),size=0.3)+
	geom_line(aes(x=pos,y=initsy,col="SY"),size=0.3)+
	scale_x_continuous(
		guide = "prism_minor",
		labels=scales::unit_format(big.mark ="",suffix="",scale=1e-3,sep=""),
		limits=c(start(ROI),end(ROI)),
		breaks=seq(floor(start(ROI)/50000)*50000,end(ROI),50000),
		minor_breaks=seq(floor(start(ROI)/10000)*10000,end(ROI),10000),
		expand=c(0,0))+
	coord_cartesian(ylim=c(0,10))+
	xlab(paste0(as.character(seqnames(ROI))," [",ROI$name,"]"," (kb)"))+
	ylab("Init")+
	scale_color_manual("",values = rfd_pal)+
	guides(colour = guide_legend(override.aes = list(size=2)))
}
)
```


### Ter plots
```{r warning=FALSE}
bs=1000
rfd_leg <- factor(c("BY","SY"))
rfd_pal <- mypal[c(1,7)]
names(rfd_pal) <- rfd_leg

terBY <- import("BigWig/TCgn_BY.bw")
terSY <- import("BigWig/TCgn_SY.bw")

pl_ter <- lapply(seq_along(CEN), function(i) {
	ROI <- suppressWarnings(trim(CEN[i]+ovl))
	featROI <- as_tibble(feat[overlapsAny(feat,ROI)]) %>% rename(featname=name) %>% filter(type %in% c("CEN","chromBY")) 
	featROI3 <- as_tibble(masked_SY[overlapsAny(masked_SY,ROI)])
	toplot_ter <- tibble(pos=start(ROI):end(ROI),
		terby=as.numeric(unlist(coverage(terBY,weight=terBY$score)[ROI])),
		tersy=as.numeric(unlist(coverage(terSY,weight=terSY$score)[ROI]))
		)
	toplot_ter2 <- toplot_ter %>% mutate(pos = floor(pos/bs)*bs+1) %>%
		group_by(pos) %>%
		summarise(
		terby = mean(terby,na.rm=T),tersy = mean(tersy,na.rm=T),
		 .groups = "drop")
pl <- ggplot(toplot_ter2)+
	geom_rect(data=featROI3,aes(xmin=start,xmax=end,ymin=0,ymax=10),fill=mypal[15],col=mypal[15])+
	geom_vline(data=featROI%>% filter(type %in% c("CEN")),aes(xintercept=start),linetype=2,alpha=0.8)+
	geom_vline(data=featROI%>% filter(type %in% c("CEN")),aes(xintercept=end),linetype=2,alpha=0.8)+
	geom_vline(data=featROI%>% filter(type %in% c("chromBY")),aes(xintercept=start),linetype=4,alpha=0.8)+
	geom_vline(data=featROI%>% filter(type %in% c("chromBY")),aes(xintercept=end),linetype=4,alpha=0.8)+
	geom_line(aes(x=pos,y=terby,col="BY"),size=0.3)+
	geom_line(aes(x=pos,y=tersy,col="SY"),size=0.3)+
	scale_x_continuous(
		guide = "prism_minor",
		labels=scales::unit_format(big.mark ="",suffix="",scale=1e-3,sep=""),
		limits=c(start(ROI),end(ROI)),
		breaks=seq(floor(start(ROI)/50000)*50000,end(ROI),50000),
		minor_breaks=seq(floor(start(ROI)/10000)*10000,end(ROI),10000),
		expand=c(0,0))+
	coord_cartesian(ylim=c(0,10))+
	xlab(paste0(as.character(seqnames(ROI))," [",ROI$name,"]"," (kb)"))+
	ylab("Ter")+
	scale_color_manual("",values = rfd_pal)+
	guides(colour = guide_legend(override.aes = list(size=2)))
}
)
```

### nanoT plots
```{r warning=FALSE}
bs=1000
rfd_leg <- factor(c("BY","SY"))
rfd_pal <- mypal[c(1,7)]
names(rfd_pal) <- rfd_leg

nanoBY <- import("BigWig/nanoT_BYBYSY.bw")
nanoSY <- import("BigWig/nanoT_SYSY.bw")

nanoT_ARS <- import("Data/ARS_nanotiming_MApadj0.01.bed")

pl_nano <- lapply(seq_along(CEN), function(i) {
	ROI <- suppressWarnings(trim(CEN[i]+ovl))
	featROI <- as_tibble(feat[overlapsAny(feat,ROI)]) %>% rename(featname=name) %>% filter(type %in% c("CEN","chromBY")) 
	featROI2 <- as_tibble(nanoT_ARS[overlapsAny(nanoT_ARS,ROI)]) %>% rename(featname=name)
	featROI3 <- as_tibble(masked_SY[overlapsAny(masked_SY,ROI)])
	toplot_nano <- tibble(pos=start(ROI):end(ROI),
		nanoby=as.numeric(unlist(coverage(nanoBY,weight=nanoBY$score)[ROI])),
		nanosy=as.numeric(unlist(coverage(nanoSY,weight=nanoSY$score)[ROI]))
		)
	toplot_nano2 <- toplot_nano %>% mutate(pos = floor(pos/bs)*bs+1) %>%
		group_by(pos) %>%
		summarise(
		nanoby = mean(nanoby,na.rm=T),nanosy = mean(nanosy,na.rm=T), 
		.groups = "drop")

pl <- ggplot(toplot_nano2)+
	geom_rect(data=featROI3,aes(xmin=start,xmax=end,ymin=0.8,ymax=2.2),fill=mypal[15],col=mypal[15])+
	geom_text(data=featROI2,aes(x=start,y=2),label="*",size=8)+
	geom_vline(data=featROI%>% filter(type %in% c("CEN")),aes(xintercept=start),linetype=2,alpha=0.8)+
	geom_vline(data=featROI%>% filter(type %in% c("CEN")),aes(xintercept=end),linetype=2,alpha=0.8)+
	geom_vline(data=featROI%>% filter(type %in% c("chromBY")),aes(xintercept=start),linetype=4,alpha=0.8)+
	geom_vline(data=featROI%>% filter(type %in% c("chromBY")),aes(xintercept=end),linetype=4,alpha=0.8)+
	geom_line(aes(x=pos,y=nanoby,col="BY"),size=0.3)+
	geom_line(aes(x=pos,y=nanosy,col="SY"),size=0.3)+
	scale_x_continuous(
		guide = "prism_minor",
		labels=scales::unit_format(big.mark ="",suffix="",scale=1e-3,sep=""),
		limits=c(start(ROI),end(ROI)),
		breaks=seq(floor(start(ROI)/50000)*50000,end(ROI),50000),
		minor_breaks=seq(floor(start(ROI)/10000)*10000,end(ROI),10000),
		expand=c(0,0))+
	coord_cartesian(ylim=c(0.8,2.2))+
	xlab(paste0(as.character(seqnames(ROI))," [",ROI$name,"]"," (kb)"))+
	ylab("nanoTiming")+
	scale_color_manual("",values = rfd_pal)+
	guides(colour = guide_legend(override.aes = list(size=2)))
}
)
```


### Composing with patchwork

```{r message=FALSE, warning=FALSE}

p_list <- list()
for (i in 1:16) 
{
pl_rfdpooled <- pl_rfd[[i]]+theme(legend.title=element_blank(),axis.title.x=element_blank(),legend.key.size = unit(0.3, 'cm'))+ylab("RFD")
pl_initpooled <- pl_init[[i]]+theme(legend.title=element_blank(),axis.title.x=element_blank(),legend.key.size = unit(0.3, 'cm'))+ylab("IC")
pl_terpooled <- pl_ter[[i]]+theme(legend.title=element_blank(),axis.title.x=element_blank(),legend.key.size = unit(0.3, 'cm'))+ylab("TC")
pl_nanopooled <- pl_nano[[i]]+theme(legend.title=element_blank(),axis.title.x=element_blank(),legend.key.size = unit(0.3, 'cm'))+ylab("RT")
pl_gen <- pl_geno2[[i]]+theme(legend.title=element_blank(),legend.key.size = unit(0.3, 'cm'))+ylab("Features")

p_list[[i]] <- pl_rfdpooled/pl_initpooled/pl_terpooled/pl_nanopooled/plot_spacer()/pl_gen+plot_layout(ncol = 1, heights = c(rep(3,4),0.6,2))
}

pp <- wrap_elements(p_list[[15]])+wrap_elements(p_list[[4]])+wrap_elements(p_list[[14]])+wrap_elements(p_list[[13]]) + plot_layout(guides="collect",ncol=2)+plot_annotation(tag_levels="A",title="Figure 4") & theme(text = element_text(face="bold"))
ggsave(plot=pp,paste0("FigArticle/Fig4.pdf"),h=14,w=10,device=cairo_pdf)

pp <- wrap_elements(p_list[[16]])+wrap_elements(p_list[[5]])+wrap_elements(p_list[[6]])+wrap_elements(p_list[[12]]) + plot_layout(guides="collect",ncol=2)+plot_annotation(tag_levels="A",title="Supplementary Figure 4") & theme(text = element_text(face="bold"))
ggsave(plot=pp,paste0("FigArticle/FigS4AD.pdf"),h=14,w=10,device=cairo_pdf)

pp <- wrap_elements(p_list[[11]])+wrap_elements(p_list[[1]])+wrap_elements(p_list[[2]])+wrap_elements(p_list[[3]]) + plot_layout(guides="collect",ncol=2)+plot_annotation(tag_levels=list(c("E","F","G","H")),title="Supplementary Figure 4") & theme(text = element_text(face="bold"))
ggsave(plot=pp,paste0("FigArticle/FigS4EH.pdf"),h=14,w=10,device=cairo_pdf)

pp <- wrap_elements(p_list[[7]])+wrap_elements(p_list[[8]])+wrap_elements(p_list[[9]])+wrap_elements(p_list[[10]]) + plot_layout(guides="collect",ncol=2)+plot_annotation(tag_levels=list(c("I","J","K","L")),title="Supplementary Figure 4") & theme(text = element_text(face="bold"))
ggsave(plot=pp,paste0("FigArticle/FigS4IL.pdf"),h=14,w=10,device=cairo_pdf)
```
